packages/fetch-api/public/index.tsx, packages/fetch-api/src/__tests__/api.test.ts, packages/fetch-api/src/api.ts, packages/types/src/pingback-event.ts
Add the emoji endpoint to the fetch-api. It doesn't support search, just returns all the emoji, therefore the only options are the `PaginationOptions`
Here is the emoji endpoint being used in a `Grid`:
=> feat(fetch-api): emoji

packages/fetch-api/src/__tests__/api.test.ts, packages/fetch-api/src/request.ts, packages/fetch-api/src/result-types.ts
No more CORS issues, we get a real error message now. The format is different than the success messages with json body consisting solely off a `message` field. I created a new type for this called `ErrorResult`
=> feat(fetch-api): better error messages available

packages/react-components/src/components/gif.tsx
Quick fix for `Overlay` api in our React components
=> fix(react-components): overlay use mouse leave

packages/react-components/src/components/gif.tsx
The aspect ratio will change when you add a height.
If you want to target the gif image for object-fit you can use `Gif.className img`
=> feat(react-components): optionally force a gif height

packages/react-components/src/components/gif.tsx
we can style a gif with padding (e.g. in a grid to make room for giphy tv), and we'd want the background and the img to receive the padding
=> feat(react-components): move background to img

packages/fetch-api/public/index.tsx, packages/fetch-api/src/__tests__/api.test.ts, packages/fetch-api/src/api.ts, packages/fetch-api/src/option-types.ts
This was already available but I added an explicit search option
Also got 100% coverage back on fetch-api
=> feat(fetch-api): search channels

packages/components/src/components/grid.tsx, packages/react-components/src/components/grid.tsx
sometimes it takes more than
100 ms to render the gifs,
(like on page load)
this will cause two fetches
=> feat(grids): increase debounce

packages/components/src/components/gif.tsx, packages/react-components/src/components/gif.tsx, packages/react-components/stories/gif.stories.tsx
Adding an `as` prop which can be eitehr `a` or `div`. This allows the use of the GIF component without the anchor attached to it. This is useful for times you want the gif lazy loading, analytics, etc. but you don't want it to link to the gif detail page.
=> GIF - Proposal for optional noLink prop

packages/components/src/components/gif.tsx, packages/react-components/src/components/gif.tsx
Making `href` prop passing to `Container` optional and `undefined` when `noLink` is set to `true`
=> Fixing noLink GIFs

packages/fetch-api/src/request.ts
Whelp, requirements changed here and we don't need the headers after all. Begins to address #58, though there may be other issues running in node
=> feat(fetch-api): sdk request headers no longer needed

packages/analytics/src/__tests__/pingback-requests.test.ts, packages/analytics/src/session.ts, packages/fetch-api/src/api.ts, packages/util/src/log.ts, packages/util/src/sdk-headers.ts, packages/util/src/webp-check.ts, packages/util/yarn.lock
I'm now able to run this is in a node environment. Fixes #58 
This will work when I release:
https://codesandbox.io/s/fetch-api-in-express-kwfq8
=> fix(node-support): check browser-only apis

packages/components/README.md, packages/components/public/grid-demo.tsx, packages/components/src/components/grid.tsx, packages/components/src/index.tsx
My plan for removing components in the Vanilla JS SDK was a bit off, returning the element and then letting the user remove the element still left the element in the `Preact` virtual dom, and a subsequent render (perhaps with a new `fetchGifs`) would re-render the existing component. 
I'm updating `remove` to `render(null)`, and then a subsequent render will create a new component instead of re-rendering the existing component. 
Fixes #65 
This is an API change so I'l l have to do a major bump. 
Also, I'm wondering if returning the element was  of any use to anybody. 
Technically it can still be accessed via: `querySelector`:
```typescript 
// the user specified class name or the default 
// class name of the component, below is `Gif.className`
target.querySelector(`.${aUsersClassName || …
```
=> fix(components): remove components properly

packages/analytics/src/__tests__/pingback-requests.test.ts, packages/analytics/src/util.ts, packages/react-components/src/components/gif.tsx
- don't append client rect if `key: position`  is passed in
- add a test
- add attributes to all pingback events
=> fix(pingback): custom attribute 

packages/components/src/components/gif.tsx, packages/react-components/src/components/gif.tsx
Noticed a quirk on Android were a `Gif` component wasn't reporting a fully visible threshold of `1` when the container it was in had an `overflow: hidden | scroll`, even though the container's size was the same as the element it was wrapping, the `threshold` was reporting at about `.996`. 
To give a little leniency to developers, and to avoid not reporting `SEEN` events because of a browser quirk, I changed the fully visible threshold to `.99`
=> fix(intersection-observer): tweak threshold to be slightly forgiving

packages/components/README.md, packages/components/src/components/carousel.tsx, packages/components/src/components/grid.tsx, packages/react-components/README.md, packages/react-components/src/components/carousel.tsx, packages/react-components/src/components/grid.tsx
This adds the possibility of adding a customised `No results` text when the response returns empty.
=> feature: add no result props when response is empty

packages/components/public/grid-demo.tsx, packages/components/src/components/carousel.tsx, packages/components/src/components/grid.tsx
I missed these props, fixes #99
=> fix(components): hide attribution missing on grid and carousel

packages/react-components/src/components/grid.tsx, packages/react-components/src/components/masonry-grid.tsx
a column's top can start with an offset
```jsx
<Grid
width={width}
columns={columns}
fetchGifs={fetchWrapped}
columnOffsets={[0,0,100,100]} // start the 3rd and 4th column 100 pixels from the top
/>
=> feat(react-components): grid column offsets from top

packages/react-components/src/components/masonry-grid.tsx
When using column offsets*, the offset needed to be incorporated into the initial values in order to determine the column target correctly. 
Bug: 
* Column offsets are an edge case where you need to push the start of the columns down, a requirement for giphy.com to show a TV in a grid
=> fix(react-components): column offsets in masonry

packages/components/src/components/attribution/index.tsx, packages/react-components/src/components/attribution/index.tsx
In an api response, sometimes a user object is an empty object, sometimes it's null. Handle the empty object scenario
=> fix(attribution): handle an empty user object

packages/fetch-api/src/api.ts, packages/fetch-api/src/request.ts
We cache requests based on url, something we don't want to do for `random()`, adding an internal option to skip the cache
=> fix(fetch-api): don't cache random requests in memory

packages/components/README.md, packages/components/src/components/carousel.tsx, packages/components/src/components/grid.tsx, packages/react-components/README.md, packages/react-components/src/components/carousel.tsx, packages/react-components/src/components/grid.tsx
- add `noLink` prop to `Grid` and `Carousel` to be passed to `Gif` components 
- update docs
`noLink` renders the `Gif` component with a `div` instead of an `a` tag. The user will define gif click functionality with `onGifClick`.
=> feat(no-link): grid and carousel components accept the noLink prop

packages/fetch-api/src/result-types.ts
Subcategories in ICategory interface changed from ICategory to ICategory[]
=> Wrong type for subcategories

packages/react-components/README.md
JIRA reference: https://giphypedia.atlassian.net/browse/IN-67
Product Brief: https://giphypedia.atlassian.net/wiki/spaces/DEV/pages/1726087342/Developer+Lifecycle+Improvements
In an attempt to highlight that developers should create separate SDK keys for every platform, i wanted to make this change to the documentation.
@giannif would love your feedback on whether this is effective wording?
Once this PR is worked through - I'll make similar changes to the Vanilla JS documentation
=> Updating language around API keys

packages/fetch-api/src/request.ts
The global variable will need to be defined before the bundles load, which it is on giphy.com
=> feat(fetch-api): global api url override

packages/fetch-api/README.md, packages/fetch-api/src/__tests__/api.test.ts, packages/fetch-api/src/api.ts, packages/fetch-api/src/option-types.ts
Add a type option for the related endpoint. type can be `gifs` or `stickers`
=> feat(fetch-api): related stickers option

packages/components/src/components/carousel.tsx, packages/components/src/components/gif.tsx, packages/components/src/components/grid.tsx, packages/react-components/src/components/attribution/overlay.tsx, packages/react-components/src/components/carousel.tsx, packages/react-components/src/components/gif.tsx, packages/react-components/src/components/grid.tsx, packages/react-components/stories/gif.stories.tsx
By default in `@giphy/react-components`, gif components will now have a border radius. It can be turned off by passing `borderRadius={0}`.
=> feat(react-components): border radius

packages/analytics/src/pingback.ts
If logging is enabled, send pingbacks with `mode=verification`
=> feat(pingback-v2): verification mode

packages/components/src/components/gif.tsx, packages/react-components/src/components/gif.tsx
Add a class name to the `Gif` component's img element after the img loads. This lets you target a transition in animation for any `Gif` component. 
Styled Component example of animating `Gif` components on a `Grid`:
```tsx
import { Gif, Grid } from '@giphy/react-components'
const growIn = keyframes`
0% {
transform: scale(0.6);
opacity: 0;
};  
100% {
transform: scale(1);
opacity: 1;
}
`
const GridWithAniimation = styled(Grid)`
.${Gif.imgClassName} {
transform: scale(0.6);
opacity: 0;
}
.${Gif.imgLoadedClassName} {
animation: ${growIn} ease-out 250ms forwards;
}
`
=> feat(components/react-components): on loaded classname

packages/fetch-api/src/__tests__/api.test.ts, packages/fetch-api/src/request.ts, packages/react-components/stories/grid.stories.tsx
If a response has no `response_id`, flag it is an error, even though it's a `200`. @ethanlu any response without a `response_id` is going to throw an error, just want to make sure that this is 100% the right thing to do
=> feat(fetch-api): handle synthetic response (api error)

packages/types/src/gif.ts, packages/util/src/gif-utils.ts
`IGif`'s `{ type: 'text' }` is returned from the `animate` endpoint
=> types(gif): text

packages/components/src/components/gif.tsx, packages/react-components/src/components/gif.tsx
setting tabindex may create a default css border around a gif when it's selected, have it `unset` as the default
=> fix(gif): css tabindex focus css

packages/react-components/stories/video.stories.tsx
There's always a difference in Percy visual testing, probably since we force autoplay.
=> percy(video): don't test video on percy

packages/react-components/src/components/grid.tsx
This PR has the objective to make Grids accept custom `layoutTypes` for pingbacks.
This is required because we are creating the `Mixed Grid`, and we want to separate the pingbacks between Mixed Grids and Normal Grids
Ticket: https://giphypedia.atlassian.net/browse/CXP-1023
Branch on **web-app**: https://github.com/Giphy/web-app/tree/CXP-1023/mixed-feed-grid-spin-web
=> Cxp 1023/mixed feed grid spin web

packages/components/src/components/video/video.tsx, packages/react-components/src/components/video/video.tsx
Change the loop counter approach to use the onended event and play, instead of the loop property of the video element
=> fix(video): less than 1s duration not triggering loop

packages/fetch-api/src/index.ts, packages/fetch-api/src/request.ts, packages/react-components/src/components/search-bar/context.tsx
DRY and for testing environments that use GIPHY_API_URL
=> feat(fetch-api): export serverUrl

packages/react-components/src/components/grid.tsx, packages/react-components/stories/grid.stories.tsx
Enable a custom loader 
```jsx
<Grid
key={term}
width={width}
columns={columns}
loader={() => <h1 style={{ textAlign: 'center' }}> 🌀 </h1>} 
fetchGifs={fetchGifs}
/>
```
=> feat(react-components): custom loader for grid

packages/components/README.md, packages/components/src/components/carousel.tsx, packages/react-components/README.md, packages/react-components/src/components/carousel.tsx, packages/react-components/stories/carousel.stories.tsx
Carousels can now have a fixed width look by setting a `gifWidth` property on the `Carousel` component:
Without fixed width:
=> feat(carousel): add a gifWidth option for fixed width carousel items

packages/react-components/src/components/grid.tsx
fix(Grid): can't perform a React state update on an unmounted component
re #277
=> fix(Grid): can't perform a React state update on an unmounted component

packages/components/src/components/gif.tsx, packages/components/src/components/grid.tsx, packages/react-components/src/components/gif.tsx, packages/react-components/src/components/grid.tsx
Our Gif component only loaded a `.gif` when on the screen using intersection observer, however that logic was missing from `.webp`, which really is all we load. Bummer of a bug here, surprised we never caught it until now
=> Fix - WebP Loading Bug

packages/brand/README.md, packages/brand/src/typography.ts, packages/components/README.md, packages/react-components/README.md
For #291
Our components are designed to work with specific fonts, but you can stop the fonts from loading by using an environment variable `GIPHY_SDK_NO_FONTS=true`.
=> add env variable to stop fonts from loading

packages/components/src/components/grid.tsx, packages/components/src/components/video/progress-bar.tsx, packages/components/yarn.lock, packages/react-components/src/components/grid.tsx, packages/react-components/stories/grid.stories.tsx, packages/react-components/yarn.lock
In some devices, like Google Pixel 2 (tested in BrowserStack) the fetch was being fired twice on the first load. I noticed that one of the reasons is because our state variable to check if `isFetching` is not really working, because we only update this state inside the debounce, so if the fetch is fired 2 times, the `isFetching` will be only updated after a few seconds and both fetches will be performed. 
This was causing this bug: https://giphypedia.atlassian.net/browse/CXP-1740 
To solve this problems I'm now changing the `isFetching` state to be changed before the bounce, so if we are in the middle of a fetch, we will not start a new debounce function.
=> set isFetching true before the debounce

packages/react-components/README.md
The component name was misspelled, corrected it to match the correct spelling.
=> Fix typo in component name

.changeset/empty-eggs-cough.md, packages/react-components/cypress/stories/emoji-variations-list.spec.tsx, packages/react-components/cypress/stories/grid.spec.tsx, packages/react-components/src/components/grid.tsx
Revert grid refactor to hooks. It had triggered a few infinite fetch loops. Will plan a refactor away from PureComponents in the future
=> React components/revert grid refactor

.changeset/angry-lamps-dream.md, .changeset/twenty-rules-relax.md, packages/fetch-api/public/index.tsx, packages/fetch-api/src/api.ts, packages/fetch-api/src/option-types.ts, packages/react-components/src/components/gif.tsx, packages/react-components/stories/gif.stories.tsx, packages/react-components/stories/grid.stories.tsx
Restructure the element tree and css of the `Gif` component, allowing it to be more easily styled with a percentage. 
- Add the percentage prop
- remove redundant width and height from inner div
- remove redundant width and height from image 
- remove unnecessary wrapper of Container with React Component
=> react-components: add percentWidth prop for Gif. fetch-api: add type videos to related fetch

.changeset/fluffy-months-play.md, .github/workflows/main.yml, .github/workflows/publish.yml, packages/fetch-api/package.json, packages/fetch-api/public/index.tsx, packages/fetch-api/src/api.ts, yarn.lock
Optional extra argument to `GiphyFetch` constructor to append additional query string params
=> fetch api extra qs params

.changeset/fresh-balloons-boil.md, packages/react-components/src/components/search-bar/search-button.tsx
- reduce size of magnifying glass
- update gradient colors
- remove border radius on left side of button
=> react-components: update search bar button design

.changeset/thirty-buses-approve.md, packages/react-components/src/components/gif.tsx, packages/react-components/src/components/search-bar/index.tsx, packages/react-components/src/components/search-bar/search-button.tsx, packages/react-components/src/components/video/video-overlay.tsx, packages/react-components/stories/gif.stories.tsx, packages/react-components/stories/search-bar.stories.tsx
- mute video overlay on document visibility change
- invoke onEnter with text value when clicking on the search bar button
- add `display: block` and `width/height 100%` to picture element inside gif component: setting picture to `display: block` is a common css reset, but if that is set then width and height need to be set to 100% in order for object-fit to work
=> react-components updates 

.changeset/poor-zoos-float.md, packages/react-components/src/index.ts
tsup otherwise treeshakes it out in the esm build
some of our components don't need use client, but for now this works
=> react-components: use cilent added to barrel file

.changeset/hungry-bulldogs-attend.md, packages/fetch-api/package.json, packages/fetch-api/src/api.ts, yarn.lock
use URLSearchParams
fixes #436
=> remove qs from fetch-api

.changeset/dull-cherries-hang.md, packages/react-components/src/components/gif.tsx, packages/react-components/src/components/grid.tsx, packages/react-components/stories/grid-editable.stories.tsx
allowing for easier data mutations
https://github.com/Giphy/giphy-js/assets/448767/ad598712-56d3-4576-b98e-d7a9ec3d40fd
=> react-components: support external state for grid 

.changeset/cuddly-owls-divide.md, packages/fetch-api/src/fetch-error.ts, packages/fetch-api/src/index.ts, packages/fetch-api/src/request.ts, packages/fetch-api/src/result-types.ts
- Raise new error subclass `GeoFetchError` to differentiate a geo-blocked response from a regular 404 response
=> Handle geo-blocked response from API

.changeset/kind-socks-relate.md, packages/fetch-api/src/paginator.ts, packages/react-components/src/components/carousel.tsx, packages/react-components/src/components/grid.tsx
For channels endpoint, there can be gifs that are hidden by the user, but yet they still affect the offset value. This is a workaround to make another request at the offset in the `next` url provided by the channels endpoint. Using that offset lets us skip to the next available gif. 
This fix will only work with a fetch gifs function that parses the offset. We do that on giphy.com. This change won't work for other SDK users unless they implement the parsing of the offset. 
It's not a common issue and only affects a small number of channels so this shouldn't be a problem
=> set a flag to ignore stop fetching
