- packages/components/src/components/gif.tsx
- packages/util/src/webp-check.ts
Just use a Promise so we only do the WebP check once
> fix(webp): promise was wrapped in function

- package.json
- packages/analytics/package.json
- packages/analytics/yarn.lock
- packages/brand/package.json
- packages/brand/yarn.lock
- packages/components/package.json
- packages/components/src/components/carousel.tsx
- packages/components/src/components/grid.tsx
- packages/components/yarn.lock
- packages/fetch-api/package.json
- packages/fetch-api/src/paginator.ts
- packages/fetch-api/src/request.ts
- packages/fetch-api/yarn.lock
- packages/react-components/package.json
- packages/react-components/src/components/carousel.tsx
- packages/react-components/src/components/gif.tsx
- packages/react-components/src/components/grid.tsx
- packages/react-components/yarn.lock
- packages/types/package.json
- packages/types/yarn.lock
- packages/util/package.json
- packages/util/yarn.lock
- yarn.lock
- react as devDep and peerDep
- react-dom as devDep
- if a fetch fails with no status, likely due to being offline, remove the cache of the promise url so it can be refetched 
- follow suggested practices for declaring default props and initial state
> cleanup: react deps, refetch, defaultProps

- packages/analytics/package.json
- packages/brand/package.json
- packages/components/package.json
- packages/fetch-api/package.json
- packages/react-components/package.json
- packages/types/src/index.ts
- packages/types/src/user.ts
- packages/util/package.json
so bundlers can generate source maps
> export more types from types, include src in the npm package

- packages/brand/src/colors.ts
> adding giphy white smoke color

- packages/react-components/src/components/gif.tsx
`Gif` component takes a `gif` prop. `hasFiredSeen` was an instance property on `Gif`. If the `gif` prop changed, the seen wouldn't fire. Changed `hasFiredSeen` to state and reseting it when the `gif` prop changes
> fix(react-components/gif): fire gif seen if gif changes

- packages/react-components/src/components/gif.tsx
- packages/react-components/stories/gif.stories.tsx
Going to be adding in `moat`. Wanted to refactor to hooks beforehand
> refactor(react-components/gif): use hooks

- package.json
- packages/types/src/gif.ts
- packages/types/src/video.ts
- packages/util/src/__tests__/gif-utils.test.ts
- packages/util/src/__tests__/git-util-best-rendition.test.ts
- packages/util/src/collections.ts
- packages/util/src/gif-utils.ts
- yarn.lock
- Add the `video:IVideo` interface to `IGif`
- Incorporate type `video` into rendition selection
> video(types/rendition-selection)

- packages/analytics/src/__tests__/pingback-requests.test.ts
- packages/analytics/src/pingback.ts
> feat(analytics): no pingback if no response id

- packages/react-components/src/components/gif.tsx
so we can use padding on the overlay
> fix(react-components): move everything in gif in a container 

- packages/components/package.json
- packages/components/src/components/gif.tsx
- packages/components/src/components/grid.tsx
- packages/components/src/util/observer.tsx
- packages/components/yarn.lock
We started the components package with a preact beta that's now been released, upgrade to the release
> upgrade(preact): no more next use semver

- packages/analytics/package.json
- packages/analytics/src/__tests__/pingback-requests.test.ts
- packages/analytics/src/send-pingback.ts
- packages/analytics/src/session.ts
- packages/analytics/yarn.lock
Generating a random id and putting it on the user object for pingbacks. The generated id is saved in local storage, and it's available globally if a developer needs to grab it via `window.giphyRandomId`
> feat(pingback): random id

- packages/components/src/components/gif.tsx
- packages/react-components/src/components/gif.tsx
- packages/util/package.json
- packages/util/src/index.ts
- packages/util/src/tracking-pixel.ts
- packages/util/yarn.lock
This lived in some HoC in web app and wasn't in the giphy grid or the giphy brand repo and therefore I forgot to port it 🤦‍♂
> fix(bottle_data): inject tags

- packages/components/src/components/gif.tsx
- packages/react-components/src/components/gif.tsx
> fix(moat): bottle data

- packages/fetch-api/src/__tests__/api.test.ts
- packages/fetch-api/src/api.ts
- packages/fetch-api/src/option-types.ts
- packages/types/src/pingback-event.ts
- add option for explore on search requests
- add pingback_id from cookie
> fix(fetch-api): add explore pingback type, add pingback_id

- packages/analytics/package.json
- packages/analytics/yarn.lock
unused dompurify is triggering github XSS warning
> fix(dep): remove unused dompurify in analytics

- packages/react-components/src/components/carousel.tsx
don't show loader element by default
> fix(carousel): infinite scroll fetching

- packages/components/package.json
- packages/components/src/components/gif.tsx
- packages/components/yarn.lock
- packages/react-components/package.json
- packages/react-components/src/components/carousel.tsx
- packages/react-components/src/components/gif.tsx
- packages/react-components/yarn.lock
- set up ssr for gif and carousel components
- remove moat
- use picture for webp detection
Grid SSR support will be in a separate PR
> fix(ssr) / refactor

- packages/fetch-api/src/request.ts
clear the memory cache every minute
> feat(fetch-api): keep requests fresh

- packages/react-components/src/components/attribution/verified-badge.tsx
- packages/react-components/src/components/gif.tsx
- packages/react-components/src/components/search-bar/search-bar-channel.tsx
- packages/react-components/src/components/search-bar/theme.ts
- packages/react-components/stories/search-bar.stories.tsx
I used a media query for condensed mode, but it also needs to be able to be set manually
> fix(search-bar): condensed mode

- packages/types/src/gif.ts
> fix(types): original_mp4 had wrong type, IMP4 should extend IRendition

- packages/analytics/package.json
- packages/analytics/src/__tests__/pingback-requests.test.ts
- packages/analytics/src/pingback.ts
- packages/analytics/src/session.ts
- packages/fetch-api/package.json
- packages/fetch-api/src/api.ts
- packages/util/browser-mock.ts
- packages/util/jestconfig.js
- packages/util/package.json
- packages/util/src/__tests__/gif-utils.test.ts
- packages/util/src/get-pingback-id.ts
- packages/util/src/index.ts
- packages/util/yarn.lock
remove the `giphy_pbid` cookie, and generate a 16 digit id on the client, saved in session storage
> don't use cookies, use session storage

- packages/react-components/README.md
- packages/react-components/src/components/carousel.tsx
- packages/react-components/src/components/grid.tsx
- packages/react-components/src/components/search-bar/index.tsx
- packages/react-components/src/util/observer.tsx
Grids and Carousels fetch more data when the loader appears on the screen. This makes the components very portable, since there are no scroll handlers, and no measuring which would cause layout thrashing. 
We'd like to though tweak this and fetch before the loader appears on the screen, to make the user experience smoother. To do so we need to configure the intersection observer that wraps the loader graphic that's used in Grids and Carousels.
A config is now exposed on the layout components to configure that intersection observer.
The example below will make the fetch when the loader is 250px away from the bottom of the scroll container:
```tsx
const target = useRef<HTMLDivElement | null>(null)
return (
// StyledScrollContainer has overflow-y: scroll
<StyledScrollContainer ref={target}> …
```
> feat(react-components): prefetch / input font family / input auto focus

- packages/fetch-api/src/request.ts
If something 400s, you probably don't want to fetch it again, however our api seems to 400 valid responses briefly and return a message "Failed to call RPC search". 
To keep things consistent and avoid any type of infinite loop in a user interface, we'll continue to cache a 400 in memory so it's not immediately fetched again, however we'll shorten the expiration to 1 second. 
This enables the "Try again?" fetch button to work when the api stops 400ing.
> feat(fetch-api): expire error fetches more quickly

- packages/fetch-api/README.md
- packages/fetch-api/public/index.tsx
- packages/fetch-api/src/__tests__/api.test.ts
- packages/fetch-api/src/api.ts
- packages/fetch-api/src/normalize/gif.ts
- packages/fetch-api/src/option-types.ts
- packages/react-components/src/components/search-bar/context.tsx
- packages/react-components/src/components/search-bar/index.tsx
New animate text endpoint exposed on the fetch api. Create an animated text gif based on a text value. Requires a new [api key](https://developers.giphy.com/dashboard/)
Example:
```typescript
const gf = new GiphyFetch('your api key')
const { data: gifs } = await gf.animate('new animated text endpoint PR!', { limit: 5 })
```
> animate text endpoint

- packages/util/src/get-pingback-id.ts
- packages/util/src/log.ts
For React Native support in the fetch api: 
Add a check for `location` and fallback to a random string function where `uuid`
> fix(react-native): for the fetch-api, add checks for unsupported location and uuid

- packages/components/src/components/carousel.tsx
- packages/components/src/components/gif.tsx
- packages/components/src/components/grid.tsx
- packages/react-components/src/components/carousel.tsx
- packages/react-components/src/components/gif.tsx
- packages/react-components/src/components/grid.tsx
> feat(components/react-components): add tabindex to gif, grid, and carousel

- packages/fetch-api/src/__tests__/api.test.ts
- packages/fetch-api/src/normalize/gif.ts
- packages/fetch-api/src/request.ts
images width and height are numbers
fixes #126
> fix(fetch-api): normalize api response

- packages/components/src/components/video/util.ts
- packages/react-components/src/components/video/util.ts
- packages/react-components/stories/video.stories.tsx
We are adding a "began" event and we are starting to fire the quartile events even if it's on a Loop
Ticket: https://giphypedia.atlassian.net/browse/CXP-846
URL: https://web-cxp-846-add-began-event-spin-web.dev.giphy.tech/
Related: [PR](https://github.com/Giphy/web-app/pull/3405)
> Cxp 846/dispatch quartile events on loop

- packages/fetch-api/package.json
- packages/fetch-api/typedoc.json
- packages/fetch-api/yarn.lock
> docs(fetch-api): typedocs

- .travis.yml
- license.js
- packages/react-components/package.json
- packages/react-components/yarn.lock
We have an `onlyAllow` array of acceptable licenses. If we use a package that doesn't match our list, travis will fail the build. 
https://giphypedia.atlassian.net/browse/SDK-843
> test(npm): test licenses

- packages/brand/package.json
- packages/brand/yarn.lock
- packages/components/package.json
- packages/components/yarn.lock
- packages/fetch-api/package.json
- packages/fetch-api/yarn.lock
- packages/react-components/package.json
- packages/react-components/yarn.lock
upgrade parcel and recreate lock files
> build(dev): upgrade parcel (used for testing) to v2

- packages/fetch-api/src/constants.ts
- packages/fetch-api/src/index.ts
- packages/fetch-api/src/request.ts
> fix(fetch-api): fix warning circular dependencies (#244)

- packages/react-components/.storybook/main.js
- packages/react-components/package.json
- packages/react-components/stories/video-player.stories.tsx
- packages/react-components/stories/video.stories.tsx
instead of hiding the stories, just hide the video element
> percy visual testing: hide video element in percy

- packages/react-components/src/components/video/index.tsx
> feat(video): auto hide controls

- packages/react-components/src/components/video/index.tsx
didn't incorporate browser mute
> fix(react-components): video onUserMute

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature.yml
Preview https://github.com/Giphy/giphy-js/tree/feat/issue-templates/.github/ISSUE_TEMPLATE
> chore: add issue templates

- packages/react-components/.percy.yml
- packages/react-components/package.json
- packages/react-components/src/components/video/index.tsx
- packages/react-components/yarn.lock
Lower title from 26px to 22px
Also fix percy storybook by upgrading deps
> react-compoonents(video-overlay): lower title size to be inline with GIPHY styling 

- packages/analytics/src/send-pingback.ts
https://giphypedia.atlassian.net/browse/XPS-969
> fix: Don't send empty events to Pingback

- packages/react-components/README.md
- packages/react-components/src/components/search-bar/context.tsx
- packages/react-components/src/components/search-bar/index.tsx
signals if the input is focused and is available in SearchContext
> react-components: add isFocused for search experience

- packages/fetch-api/src/api.ts
- packages/fetch-api/src/index.ts
- packages/fetch-api/src/result-types.ts
- packages/react-components/README.md
- packages/react-components/cypress/stories/search-bar.spec.tsx
- packages/react-components/package.json
- packages/react-components/src/components/search-bar/cancel-icon.tsx
- packages/react-components/src/components/search-bar/context.tsx
- packages/react-components/src/components/search-bar/index.tsx
- packages/react-components/src/components/search-bar/suggestion-bar/index.tsx
- packages/react-components/stories/mock-requests.ts
- packages/react-components/stories/search-bar.stories.tsx
- packages/react-components/yarn.lock
Have the search bar fetch channels and update the display with channel prefix display. 
Can be disabled with `shouldFetchChannels={false}`
> React components - search bar updates

- packages/fetch-api/src/fetch-error.ts
- packages/fetch-api/src/request.ts
Makes debugging easier especially when running on the server
> fetch-api: add url to error message

- packages/react-components/src/components/gif.tsx
Fixes an SSR hydration warning
> fix:react-components ssr with Gif overlay

- .changeset/moody-frogs-appear.md
- packages/analytics/package.json
- packages/brand/package.json
- packages/fetch-api/package.json
- packages/react-components/package.json
- packages/util/package.json
As suggested by: https://publint.dev
> Build: add types to exports in package json

- .changeset/great-beans-switch.md
- packages/react-components/src/components/gif.tsx
Remove css that hides default browser keyboard focus
> a11y: remove css that hides keyboard focus

- .changeset/few-cobras-switch.md
- packages/react-components/package.json
- yarn.lock
> @giphy/react-components: styled components as dev/peer dep

- .changeset/pretty-waves-hide.md
- .github/workflows/main.yml
- .github/workflows/publish.yml
- packages/react-components/src/components/carousel.tsx
- packages/react-components/src/components/emoji-variations-list.tsx
- packages/react-components/src/components/grid.tsx
- packages/react-components/src/components/loader.tsx
- packages/react-components/src/components/search-bar/context.tsx
- packages/react-components/src/components/search-bar/index.tsx
- packages/react-components/src/components/video/index.tsx
- packages/react-components/src/components/video/progress-bar.tsx
- packages/react-components/src/components/video/video-overlay.tsx
Fixes #414 by adding `$` to all styled component props
> react-components: styled components use transient props

- .changeset/hip-monkeys-notice.md
- packages/react-components/src/components/search-bar/search-button.tsx
it seems to be caused by keyframe animations
> ssr: fix styled components hydration warning

- .changeset/silly-dots-juggle.md
- packages/react-components/src/components/video/index.tsx
- packages/react-components/src/components/video/video.tsx
- allow hiding the title
- fix an issue with SSR and the video player ref
> Video player updates

- .changeset/three-stingrays-tell.md
- packages/react-components/src/components/bottle-data.tsx
- packages/react-components/src/components/grid.tsx
- fix pixel firing because of timestamp
- simplify grid columns
> React components fixes
